import { BusinessItem } from '../types/database.types';

export const mockBusinesses: BusinessItem[] = [
  {
    id: 'b-1',
    slug: 'alkuraimi-bank',
    name: 'بنك الكريمي للتمويل الأصغر الإسلامي',
    category: 'banks',
    categoryName: 'بنوك ومصارف',
    city: 'صنعاء',
    district: 'شارع التحرير - المركز الرئيسي',
    phone: '770123456',
    whatsapp: '967770123456',
    website_url: 'https://alkuraimi.com',
    logo_url: 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?w=150',
    cover_url: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200',
    yr_score: 98,
    rating: 4.8,
    reviews_count: 310,
    price_range: 'خدمات مصرفية',
    hours: '8:00 ص - 4:00 م',
    is_open_now: true,
    badge_type: 'gold',
    claim_status: 'CLAIMED',
    quote_text: 'تطبيق كريمي جوال يسهل كل المعاملات والتحويلات وسداد الفواتير فوراً.',
    services: ['حسابات جارية وتوفير', 'تمويل أصغر إسلامي', 'تطبيق كريمي جوال', 'بطاقات صراف آلي مسبقة الدفع', 'خدمة كوراك السريعة'],
    description: 'بنك رائد في تقديم الخدمات المصرفية والتمويلية الإسلامية في جميع محافظات الجمهورية اليمنية مع أكثر من 240 فرعاً.'
  },
  {
    id: 'b-2',
    slug: 'tadhamon-bank',
    name: 'بنك التضامن الدولي الإسلامي',
    category: 'banks',
    categoryName: 'بنوك ومصارف',
    city: 'صنعاء',
    district: 'شارع الزبيري',
    phone: '771223344',
    whatsapp: '967771223344',
    website_url: 'https://tadhamonbank.com',
    logo_url: 'https://images.unsplash.com/photo-1501167786227-4cba60f6d58f?w=150',
    cover_url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200',
    yr_score: 96,
    rating: 4.7,
    reviews_count: 185,
    price_range: 'خدمات مصرفية',
    hours: '8:00 ص - 3:30 م',
    is_open_now: true,
    badge_type: 'gold',
    claim_status: 'CLAIMED',
    quote_text: 'خدمات مصرفية دولية وبطاقات فيزا وماستركارد العالمية المعتمدة.',
    services: ['محفظة محفظتي الإلكترونية', 'بطاقات فيزا وماستركارد', 'تمويل الشركات الكبرى', 'اعتمادات مستندية دولية'],
    description: 'مؤسسة مصرفية يمنية عريقة تقدم حلولاً استثمارية ومالية متطورة للأفراد والشركات محلياً ودولياً.'
  },
  {
    id: 'b-3',
    slug: 'alnejm-exchange',
    name: 'شركة النجم للصرافة والتحويلات',
    category: 'exchanges',
    categoryName: 'شركات صرافة',
    city: 'صنعاء',
    district: 'شارع الدائري الغربي',
    phone: '773334445',
    whatsapp: '96773334445',
    website_url: 'https://alnejm.ye',
    logo_url: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=150',
    cover_url: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=1200',
    yr_score: 97,
    rating: 4.8,
    reviews_count: 420,
    price_range: 'حوالات وصرافة',
    hours: '8:00 ص - 10:00 م',
    is_open_now: true,
    badge_type: 'gold',
    claim_status: 'CLAIMED',
    quote_text: 'أكبر شبكة تحويلات مالية فورية تربط جميع المدن والقرى اليمنية بأمان وسرعة.',
    services: ['شبكة النجم للحوالات الفورية', 'صرافة العملات الأجنبية', 'سداد باقات وفواتير الاتصالات', 'حوالات دولية سريعة'],
    description: 'شبكة الصرافة والتحويلات الأكثر انتشاراً في اليمن مع أكثر من 1800 نقطة خدمة ووكيل معتمد.'
  },
  {
    id: 'b-4',
    slug: 'alamqi-exchange',
    name: 'شركة العمقي وإخوانه للصرافة',
    category: 'exchanges',
    categoryName: 'شركات صرافة',
    city: 'عدن',
    district: 'كريتر - الشارع الرئيسي',
    phone: '774445556',
    whatsapp: '96774445556',
    website_url: 'https://alamqi.com',
    logo_url: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=150',
    cover_url: 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=1200',
    yr_score: 96,
    rating: 4.7,
    reviews_count: 360,
    price_range: 'حوالات وصرافة',
    hours: '8:00 ص - 9:30 م',
    is_open_now: true,
    badge_type: 'gold',
    claim_status: 'CLAIMED',
    quote_text: 'شبكة العمقي إكسبرس تضمن تسليم الحوالات لحظياً في كافة المحافظات.',
    services: ['العمقي إكسبرس للحوالات', 'صرافة العملات الرئيسية', 'حسابات الصرافة التجارية', 'خدمات دفع المرتبات'],
    description: 'إحدى أعرق شركات الصرافة في اليمن ذات ثقة عالية وانتشار واسع في حضرموت وعدن والمحافظات.'
  },
  {
    id: 'b-5',
    slug: 'jeeb-wallet',
    name: 'محفظة جيب الإلكترونية (Jeeb)',
    category: 'wallets',
    categoryName: 'محافظ إلكترونية',
    city: 'صنعاء',
    district: 'خدمة رقمية في جميع المحافظات',
    phone: '777000111',
    whatsapp: '967777000111',
    website_url: 'https://jeeb.ye',
    logo_url: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=150',
    cover_url: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=1200',
    yr_score: 97,
    rating: 4.8,
    reviews_count: 510,
    price_range: 'دفع رقمي مجاني',
    hours: 'خدمة رقمية 24/7',
    is_open_now: true,
    badge_type: 'gold',
    claim_status: 'CLAIMED',
    quote_text: 'المحفظة الإلكترونية الأسرع لسداد الفواتير وتحويل الأموال والشراء برمز QR.',
    services: ['دفع المشتريات برمز QR', 'سداد فواتير الكهرباء والمياه والإنترنت', 'تحويل فوري بدون عمولة', 'شحن المحفظة من أي صراف'],
    description: 'تطبيق المحفظة الرقمية الرائد في اليمن لتحويل الأموال وسداد المشتريات والخدمات بكل سهولة وأمان.'
  },
  {
    id: 'b-6',
    slug: 'shaibani-royal-restaurant',
    name: 'مطاعم الشيباني رويال الملكية',
    category: 'restaurants',
    categoryName: 'مطاعم ومأكولات',
    city: 'صنعاء',
    district: 'شارع الستين الجنوبي - فج عطان',
    phone: '770889900',
    whatsapp: '967770889900',
    website_url: 'https://shaibanirest.ye',
    logo_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=150',
    cover_url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1200',
    yr_score: 98,
    rating: 4.9,
    reviews_count: 620,
    price_range: '$$$',
    hours: '11:00 ص - 1:00 ص',
    is_open_now: true,
    badge_type: 'gold',
    claim_status: 'CLAIMED',
    quote_text: 'الفحسة والسلتة الملكية والمشاوي الطازجة بأجواء عائلية فاخرة وخدمة 5 نجوم.',
    services: ['أجنحة وقاعات عائلية VIP', 'بوفيه مفتوح وحفلات', 'توصيل طلبات سريع', 'مواقف سيارات واسعة مع حراسة'],
    description: 'أرقى مطاعم المأكولات اليمنية التراثية والمشويات في العاصمة صنعاء بضيافة ملكية فريدة.'
  },
  {
    id: 'b-7',
    slug: 'hadramout-restaurant',
    name: 'مطعم حضرموت الدولي للمأكولات',
    category: 'restaurants',
    categoryName: 'مطاعم ومأكولات',
    city: 'صنعاء',
    district: 'شارع حدة - أمام مجمع حدة',
    phone: '771987654',
    whatsapp: '967771987654',
    website_url: 'https://hadramout.ye',
    logo_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=150',
    cover_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=1200',
    yr_score: 96,
    rating: 4.7,
    reviews_count: 340,
    price_range: '$$',
    hours: 'مفتوح 24 ساعة',
    is_open_now: true,
    badge_type: 'gold',
    claim_status: 'CLAIMED',
    quote_text: 'أفضل تجربة للمندي والمظبي التراثي واللحوم الطازجة والأسماك المشوية.',
    services: ['جلسات عائلية خاصة', 'مظبي ومندي على الحطب', 'خدمة سفري وتوصيل', 'دفع إلكتروني متوفر'],
    description: 'أصالة الطبخ الحضرمي واليمني العريق واللحوم البلدية الطازجة على مدار 24 ساعة.'
  },
  {
    id: 'b-8',
    slug: 'taj-sheba-hotel',
    name: 'فندق تاج سبأ الدولي (5 نجوم)',
    category: 'hotels',
    categoryName: 'فنادق وسياحة',
    city: 'تعز',
    district: 'وسط المدينة - إطلالة جبل صبر',
    phone: '772111222',
    whatsapp: '96772111222',
    website_url: 'https://tajsheba.ye',
    logo_url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=150',
    cover_url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200',
    yr_score: 95,
    rating: 4.7,
    reviews_count: 190,
    price_range: '$$$$',
    hours: 'استقبال وحجوزات 24/7',
    is_open_now: true,
    badge_type: 'gold',
    claim_status: 'CLAIMED',
    quote_text: 'أجنحة فندقية ملكية فاخرة ومسابح وقاعات مؤتمرات مجهزة بأحدث التقنيات.',
    services: ['أجنحة VIP فندقية', 'بوفيه إفطار مفتوح', 'نادي صحي ورياضي ومسبح', 'خدمة نقل واستقبال المطار'],
    description: 'فندق 5 نجوم يقدم خدمات ضيافة فندقية راقية لرجال الأعمال والسياح والعائلات بأعلى المعايير العالمية.'
  },
  {
    id: 'b-9',
    slug: 'coral-hotel-aden',
    name: 'فندق كورال عدن الدولي (Coral Aden)',
    category: 'hotels',
    categoryName: 'فنادق وسياحة',
    city: 'عدن',
    district: 'خور مكسر - ساحل أبين',
    phone: '775112233',
    whatsapp: '967775112233',
    website_url: 'https://coraladen.ye',
    logo_url: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=150',
    cover_url: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=1200',
    yr_score: 97,
    rating: 4.8,
    reviews_count: 280,
    price_range: '$$$$',
    hours: 'استقبال وحجوزات 24/7',
    is_open_now: true,
    badge_type: 'gold',
    claim_status: 'CLAIMED',
    quote_text: 'إطلالة بحرية ساحرة على شاطئ أبين مع خدمات فندقية متكاملة ومطاعم شاطئية.',
    services: ['غرف وأجنحة مطلة على البحر', 'مسبح خارجي فاخر', 'مطعم مأكولات بحرية وشرقية', 'قاعات مؤتمرات واجتماعات'],
    description: 'أرقى منتجعات وفنادق العاصمة المؤقتة عدن مع إطلالات بانورامية خلابة على ساحل البحر العربي.'
  },
  {
    id: 'b-10',
    slug: 'alasria-store',
    name: 'متجر العصرية للجوالات والإلكترونيات',
    category: 'shops',
    categoryName: 'متاجر وتسوق',
    city: 'صنعاء',
    district: 'شارع صخر - مجمع الإلكترونيات',
    phone: '778889990',
    whatsapp: '967778889990',
    website_url: 'https://alasria.ye',
    logo_url: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=150',
    cover_url: 'https://images.unsplash.com/photo-1534452203293-494d7ddbf7e0?w=1200',
    yr_score: 96,
    rating: 4.8,
    reviews_count: 215,
    price_range: '$$$',
    hours: '9:00 ص - 10:00 م',
    is_open_now: true,
    badge_type: 'gold',
    claim_status: 'CLAIMED',
    quote_text: 'ضمان سنة كاملة معتمد وأسعار منافسة جداً على الهواتف والشواحن الأصلية كود YR20.',
    services: ['ضمان استبدال معتمد', 'قطع غيار وشواحن أصلية', 'صيانة فورية للأجهزة', 'كود خصم حصري YR20'],
    description: 'المركز الرائد في اليمن لبيع وتوزيع أحدث الهواتف الذكية (Apple, Samsung, Xiaomi) والإكسسوارات الأصلية.'
  },
  {
    id: 'b-11',
    slug: 'german-saudi-hospital',
    name: 'المستشفى السعودي الألماني - صنعاء',
    category: 'health',
    categoryName: 'صحة ومستشفيات',
    city: 'صنعاء',
    district: 'شارع الستين الشمالي',
    phone: '775556667',
    whatsapp: '967775556667',
    website_url: 'https://sghsanaa.com',
    logo_url: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?w=150',
    cover_url: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?w=1200',
    yr_score: 97,
    rating: 4.8,
    reviews_count: 430,
    price_range: 'رعاية طبية تخصصية',
    hours: 'طوارئ وعيادات 24/7',
    is_open_now: true,
    badge_type: 'gold',
    claim_status: 'CLAIMED',
    quote_text: 'رعاية صحية بمعايير عالمية ونخبة من كبار الاستشاريين وأحدث غرف العمليات.',
    services: ['طوارئ وعناية مركزة 24 ساعة', 'جراحة القلب والقسطرة', 'مختبرات وأشعة مقطعية ورنين', 'عيادات تخصصية شاملة'],
    description: 'الصرح الطبي الأكبر في اليمن لتقديم الرعاية الصحية التخصصية والعمليات الجراحية المتقدمة.'
  },
  {
    id: 'b-12',
    slug: 'raha-transport',
    name: 'شركة راحة للنقل البري الدولي',
    category: 'transport',
    categoryName: 'سيارات ونقل',
    city: 'صنعاء',
    district: 'شارع تعز - محطة النقل الدولية',
    phone: '770998877',
    whatsapp: '967770998877',
    website_url: 'https://rahatransport.ye',
    logo_url: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=150',
    cover_url: 'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=1200',
    yr_score: 94,
    rating: 4.6,
    reviews_count: 310,
    price_range: 'رحلات دولية ومحلية',
    hours: 'حجوزات 24/7',
    is_open_now: true,
    badge_type: 'gold',
    claim_status: 'CLAIMED',
    quote_text: 'أسطول حافلات حديث ومريح لرحلات العمرة والرياض وجدة ومختلف المحافظات.',
    services: ['رحلات يومية إلى السعودية (مكة/الرياض/جدة)', 'حافلات VIP بدرجة رجال الأعمال', 'شحن طرود وأمانات سريعة', 'خدمة حجز إلكتروني'],
    description: 'الشركة الأولى في خدمات النقل البري الدولي والسياحي في اليمن بأعلى مستويات الراحة والأمان.'
  }
];
